### ISSUE TITLE
Global parameter naming is confusing.

### ISSUE THREAD

**Issue by amjjbonvin** [i-VRESSE/workflow-builder#120]
Uploading of PDB files occurs via the `Global parameter` menu, but this is confusing for users (it was for me). 
It also reads now more like a title to the sections below it rather than a menu item for inputting parameters and data.

May-be an idea to change its name to `Global parameters & input molecules`

**Comment by sverhoeven** [comment]
In #123 I made the form for global parameters be initially shown. See https://deploy-preview-123--wonderful-noether-53a9e8.netlify.app/ .Does this help?

**Comment by sverhoeven** [comment]
And in #144 made the molecules form field red.
