### ISSUE TITLE
Warn when parameters are invalid

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/workflow-builder#15]
The global parameters are required. This is only reported to user when he/she make changes and tries to submit them.
Currently no nodes or node parameters are required, but can still be invalid when a incomplete workflow is uploaded.

It would be nice that the user is somehow warned that part of the workflow is not valid or incomplete.

A solution could be to add warning signs next to the `configure global parameters` button and next to each workflow node.

**Comment by rvhonorato** [comment]
Just a note, not sure if we will have user associated tokens to check their level but if we end up having we should just expose the ones that are invalid despite their tier

**Comment by amjjbonvin** [comment]
We could simply allow users to switch between different views from easy to expert and finally guru. (Or even more)

**Comment by rvhonorato** [comment]
> Sense and simplicity!

**Comment by sverhoeven** [comment]
With https://github.com/i-VRESSE/workflow-builder/pull/144 user get errors they have to fix on load.

![i-vresse-workflow-builder netlify app_ (4)](https://github.com/user-attachments/assets/7bcf5f9f-7e4a-490c-a7f9-c1ce9461b75a)
