### ISSUE TITLE
Handling files

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/workflow-builder#2]
The workflow definition file needs to have data files like pdb files. When on the command line it makes sense to store paths to those dataf files in the workflow definition file. However this build is a web application running in the browser which makes it less obvious where files are. For example files locally for the user might not be available on the server where the workflow will be executed. So the files will need to be transferred and the workflow updated accordingly.

I see several options
1. Inline the files as data URLs inside workflow definition file
2. Create zip archive which has workflow definition file and data files inside. The workflow definition uses relative paths to data files as data values.
3. Paths inside workflow definition file are relative to where it is saved on disk. It is up to who ever or what ever downloads the workflow file to make sure paths resolve correctly.
4. Define a directory where data files can be found and use relative paths to data files inside workflow definition file.

**Comment by joaomcteixeira** [comment]
I think option 2. is a good one. `molecules` paths in the workflow definition can directly point to the PDB file because when unpacking both are in the same folder. In this way, when creating the workflow online, you only need to track the file name and extension. I am not aware of all possible implications, but I think option 2 is quite neutral to all possible usages and derivatives.
Cheers,

**Comment by amjjbonvin** [comment]
This is also inline with what we are currently doing in haddock3, define all relative paths to allow remote execution.


> I think option 2. is a good one. molecules paths in the workflow definition can directly point to the PDB file because when unpacking both are in the same folder. In this way, when creating the workflow online, you only need to track the file name and extension. I am not aware of all possible implications, but I think option 2 is quite neutral to all possible usages and derivatives.

**Comment by sverhoeven** [comment]
Using zip file atm
