### ISSUE TITLE
Collapsible sub forms

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/workflow-builder#23]
The topoaa module has 20 parameters called `mol??` which are objects by themselves. Each with 10 sub parameters. This gives for a very long form. 

It would be nice if all the non-first ones could be collapsed. Clicking on the name of the parameter should expand and show the form with all the sub parameters again. This could be done with a react-json-schema-form custom widget like https://github.com/RXNT/react-json-schema-form-extras#collapsible-fields-collapsible .

**Comment by amjjbonvin** [comment]
The number of those mol?? related parameters will depend on the number of molecules that will be docked.

If a user sets up a run from scratch, this should be the first question to ask. And then define as many molecule forms as the defined number of molecules.

**Comment by rvhonorato** [comment]
This is how I handle this haddock2.5, not sure if it helps:

```javascript
// -------------------------------------------------------------------- //
// Add and remove input cards
var molCards = document.querySelectorAll("[id*='param-input-']");

var addMolElement = document.getElementById("add-mol");
addMolElement.addEventListener("click", function () {
    for (let i = 0; i < molCards.length; i++) {
        if (molCards[i].style.display == "none") {
            molCards[i].style.display = "block";
            // when you add a new card its input then becomes required
            partner_count++;
            break
        }
    };
    // Update the active/passive fields of all param-input
    var total_nb = 0;
    for (let i = 0; i < molCards.length; i++) {
        if (molCards[i].style.display == "block") {
            total_nb++;
        }
    }
    for (let i = 1; i < total_nb+1; i++) {
        for (let j = 1; j < total_nb; j++){
            document.getElementById('p'+ i + '_' + j + '_param').style.display ="block";
        }
    }
});

var removeMolElement = document.getElementById("remove-mol");
removeMolElement.addEventListener("click", function () {
    for (let i = molCards.length; i > 0; i--) {
        if (molCards[i - 1].style.display == "block") {
            molCards[i - 1].style.display = "none";
            // when you remove a new card its input it not  required
            partner_count--;
            // FIXME: here we must also clean the card
            break
        }
    }
});
```

**Comment by joaomcteixeira** [comment]
On top of everything that was said before, we will be working to have only `mol1` defined in the `defaults.yaml` file and allow the user to expand and write `mol2`, `mol3`, etc, if needed. We can do this because all parameters in `mol` are the same, except for `prot_segid` that is a cycle from `A-Z`.

**Comment by sverhoeven** [comment]
Configuration in the uiSchema of the catalog could be

```json
{
    "mol1": {
        "ui:field": "collapsible",
        "ui:collapsed": false
    }
}
```

Any property which is of type object can be rendered with a collapse/expand button. With ` "ui:field": "collapsible"` the sub form of the object will be initially rendered collapsed. To render sub form initially expanded set `ui:collapsed` uiSchema field to `false`.

**Comment by sverhoeven** [comment]
Parameters with same group are now shown in the form in a sub-form which is initially collapsed. 

Regarding comment of @joaomcteixeira we should come up with how to define this in haddock3 defaults.yaml file.
Something like
```yaml
mol:
  type: list
  maxitems: general/molecules.length
  properties:
    prot_segid:
      default: '[A-Z][index]'
      type: string
      minchars: 0
      maxchars: 4
      title: Segment ID
      short: Segment ID assigned to this molecule
      long: Segment ID assigned to this molecule in CNS. Used to distinguish different molecules
      group: 'molecule'
      explevel: easy
...
```
Use `maxitems` with a JSON pointer to the number of molecules uploaded in the general parameters.
Use `default` with range so the third mol should have C as default for prot_segid

**Comment by sverhoeven** [comment]
Topoaa module with guru level now shows

![i-vresse-workflow-builder netlify app_ (3)](https://github.com/user-attachments/assets/fa47228d-f109-4420-b569-9290feea66b0)

which makes form short initially.
