### ISSUE TITLE
Group parameters

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/workflow-builder#25]
In haddock3 each parameter per module can have a group associated with it. The form should show the parameters that belong to the same group in a nested way.

I tried to implement it by grouping the parameters in a JSON schema object in the catalog at https://github.com/i-VRESSE/workflow-builder/blob/d464932155cb6321281be40d7af07b92c4823ee0/util/generate_haddock3_catalog.py#L188-L198 , but that requires that during the reading/writing of workflow config files the parameters should be grouped/ungrouped resp. It is nicer to give the form component ungrouped parameters and have it group them internally, show the form with grouped parameters and return ungrouped parameters.

**Comment by joaomcteixeira** [comment]
A quick comment, parameters not belonging to any group can be shown at the top of the menu. Normally the first parameters in the YAML files are non grouped and the others will have groups. We have not yet annotated all parameters to their respective groups. I will do that in the following days. I am keeping [here a link](https://github.com/haddocking/haddock3/tree/0bc47778366b61c9fa733d0b7063c212db955dee/src/haddock/modules) to the commit with the right groups as noted by @amjjbonvin just before we adopted the YAMLs.

**Comment by sverhoeven** [comment]
Implemented in #33
