### ISSUE TITLE
Derive catalog from haddock3 module configs

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/workflow-builder#4]
See https://github.com/haddocking/haddock3/pull/274

**Comment by sverhoeven** [comment]
The node pararmeters are derived from haddock3

The global parameters are not derived from haddock, but hardcoded at https://github.com/i-VRESSE/workflow-builder/blob/main/util/generate_haddock3_catalog.py#L168-L185

**Comment by joaomcteixeira** [comment]
Hi, @sverhoeven last Friday and today we updated https://github.com/haddocking/haddock3/pull/274 with cleaned YAMLs and keys. Making sure you won't miss them :wink: @amjjbonvin started already adding some `titles`, `short`, and `longs`.

**Comment by sverhoeven** [comment]
Since #22 have been parsing the defaults.yaml files from haddock3.
