### ISSUE TITLE
Pre-fill defaults in node configurator

### ISSUE THREAD

**Issue by Peter9192** [i-VRESSE/workflow-builder#54]
While testing, I often encounter empty input elements in the node config. It would be nice if the defaults were pre-filled in light-grey or so, to get a hint about the type of values that make sense, and whether it is necessary to change it.

**Comment by sverhoeven** [comment]
Almost all parameters are optional, required parameters have `*` in label, maybe we can make it more obvious which parameters are required. 

We are working on getting a descriptions on more parameters. The description is shown under the input field in light-grey. 

We could add [placeholder](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-placeholder) with an example value, but for most parameters it would be `123` which is not that helpful.
