### ISSUE TITLE
Emptying a previously entered input causes error

### ISSUE THREAD

**Issue by Peter9192** [i-VRESSE/workflow-builder#60]
For example for haddock3 easy, topology, topoaa, mol1, Segment ID

first I enter a value, `B` , press submit, watch toml change. 
then I remove the value `B`, leaving the field empty, and submit again.

I get 
```
Something went terribly wrong.
toml can not stringify "undefined" type value
```

**Comment by bvreede** [comment]
![image](https://user-images.githubusercontent.com/5747405/160844070-83b27e73-a091-4116-a77f-da11e841c47e.png)

**Comment by bvreede** [comment]
This seems to be a required field? It does not show a `*` as mentioned in #54. Should it?

The same problem appeared in #53 when emptying fields in a table that were previously filled. However, this was fixed when merging main into this branch.

**Comment by sverhoeven** [comment]
'*' is for required fields, see the global parameters > 'Run directory*' or https://rjsf-team.github.io/react-jsonschema-form/ for an example of an required field.

**Comment by sverhoeven** [comment]
Unable to reproduce anymore after #144 and #158 , please reopen when you can reproduce error.
