### ISSUE TITLE
Workflow text renders [object Object] instead of plain text

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/workflow-builder#74]
Occasionally, the text box doesn't render properly (e.g. `[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]`. Toggling visual/text usually solves the issue.

From https://github.com/i-VRESSE/workflow-builder/pull/62#pullrequestreview-962033686

**Comment by sverhoeven** [comment]
I have seen it as well, but I was always triying to implement/solve something else.

Would be great to find a way to reproduce this behavior.

**Comment by bvreede** [comment]
This is very consistent behavior for me (MacOSX, I've tried in Brave and Safari, both behave the same). When showing the Workflow Text for the first time, `[object Object] (etc)` shows (except when no workflow elements have been added at all — then the screen is empty); toggling Visual/Text indeed solves the issue, and it does not return.

**Comment by bvreede** [comment]
At this point, in my system (and that of @sverhoeven) the production version still causes the error, but locally we cannot reproduce it.
Inspecting the component that has the `[object Object]` text, it looks like the text itself does get passed to the component, but it does not show up on the page:

<img width="1366" alt="Screenshot 2022-06-30 at 10 59 56" src="https://user-images.githubusercontent.com/5747405/176637777-b1a47a5d-eca8-4fb9-8f18-fad5e2ae7908.png">

This seems to correspond to the `SyntaxHighlighter` component (inspecting the local rendering):

<img width="1135" alt="Screenshot 2022-06-30 at 11 48 13" src="https://user-images.githubusercontent.com/5747405/176647446-78a16177-16ae-4f46-a4c4-b10aec3af43a.png">

**Comment by sverhoeven** [comment]
Should be fixed with #90 PR, reopen or recreate when it happens again
