### ISSUE TITLE
Give index to uploaded molecules to make clear which paramters belong to which molecule

### ISSUE THREAD

**Issue by amjjbonvin** [i-VRESSE/workflow-builder#76]
Currently when uploading molecules, they appear in the interface sequentially without any index about which molecule it is. This is fine for say two molecule docking. But when we will have multiple molecules it will be hard to keep track of which molecule we are speaking about when defining parameters further down the workflow (e.g. the topoaa module)

So may-be adding a molecule index and the associated PDB name for molecule-related blocks might make things clearer to the user.

**Comment by sverhoeven** [comment]
Related to https://github.com/i-VRESSE/workflow-builder/issues/57
