### ISSUE TITLE
Support resdic_ parameter

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/workflow-builder#77]
The rsmdmatrix module introduced the `resdic_` parameter. Which is an object where the user must select the key and value.

See definition at https://github.com/haddocking/haddock3/blob/main/src/haddock/modules/analysis/rmsdmatrix/defaults.yaml#L13-L25

See PR that introduced it at https://github.com/haddocking/haddock3/pull/414

# Schema

In JSON schema this could be modelled as:
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "resdic": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "number",
                    "format": "residue"
                },
                "uniqueItems": true
            },
            "propertyNames": {
                "pattern": "^[A-Z]$",
                "format": "chain"
            },
            "maxPropertiesFrom": "molecules"
        }
    },
    "additionalProperties": false
}
```
In PR #62 the format `residue` and `chain` are introduced for arrays, they should be changed to also work with a object of additionalProperties. In this schema I also suggest to use `"maxPropertiesFrom": "molecules"` to define where the chain/residue info comes from.
The form could like 
![rjsf-team github io_react-jsonschema-form_](https://user-images.githubusercontent.com/1713488/169490064-92eaa651-cd74-4452-9ddc-6cfa5d6a73b6.png)

# Mol aware schema

When a user already supplied molecules (here molecules have chain A and B with some residue numbers) then the schema for the form could be rewritten to 
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "A": {
            "type": "array",
            "items": {
                "type": "number",
                "enum": [
                    1,
                    2,
                    3,
                    4,
                    5
                ]
            },
            "uniqueItems": true
        },
        "B": {
            "type": "array",
            "items": {
                "type": "number",
                "enum": [
                    6,
                    7,
                    8,
                    9,
                    10
                ]
            },
            "uniqueItems": true
        }
    },
    "additionalProperties": false
}
```
The form could look like
![rjsf-team github io_react-jsonschema-form_ (1)](https://user-images.githubusercontent.com/1713488/169490273-8de81d58-f902-4325-9ea7-65b3de858d87.png)

**Comment by sverhoeven** [comment]
The key is the chain identifier, the valid choices could be the unique set of all chains found in all molecules (uploaded PDB files). 

However it could be that chain A in molecule 1 and chain A in molecules 2 have different residue numbers, because the molecules are different. What are then valid choices for the residue numbers for `resdic_A`? 
@mgiulini do you know?

**Comment by amjjbonvin** [comment]
If this is dealing with an ensemble of starting structures, then they should all be consistent in principle if residues were to be defined in some parameter settings. But does not applies to the scoring workflow

In principle HADDOCK3 can handle molecules with different numbering / sequences within the same ensemble.

**Comment by mgiulini** [comment]
@amjjbonvin Indeed, we should introduce a check that prevents the usage of the `resdic` parameter on heterogeneous ensembles.

@sverhoeven `resdic_A` can contain all the residues present in chain A, possibly randomly sorted and without repetitions.
